### ISSUE TITLE
oso.Get does not work as documented

### ISSUE THREAD

**Issue by DonDebonair** [osohq/go-oso-cloud#4]
As I understand it correctly, the difference between `oso.Get(...)` and `oso.Query(...)` is that the former returns only facts that were explicitly stored in Oso Cloud, while the latter will also return implicit facts such as roles that are inherited from a related resource.

I want to query only the explicitly submitted roles a user has on a specific resource, so I tried something like the following:

```go
facts, err := oso.Get("has_role", &userInstance, nil, &resourceInstance)
```

And I would expect it to return all the roles that have been explicitly added to Oso Cloud for the provided user on the provided resource.

The aforementioned code is not valid however, because `oso.Get(...)` expects _values_ to be passed in as arguments, as opposed to pointers (which is what `oso.Query(...)` expects). This is different from [what is documented](https://www.osohq.com/docs/reference/client-apis/go#list-facts-osogetname-args) (see second example).

I tried passing in an empty `oso.Instance` instead of `nil`, but that gives a nil pointer dereference error.

I think this is a bug? How can I get only the roles that have been explicitly defined for a user on a resource?

**Comment by killpack** [comment]
Thanks for the bug report- looks like you're right, this appears to be busted. Will escalate this internally.

**Comment by killpack** [comment]
We just published a new release that addresses this, and the docs should be updated imminently.

Please upgrade to 1.1.1, at which point you'll be able to use an empty `Instance` instead of `nil` to represent a wildcard-

`facts, err := oso.Get("has_role",   oso.Instance{Type: "User", ID: "bob"}, oso.Instance{}, oso.Instance{Type: "Repository", ID: "anvils"}) // get all bob's roles on the anvils repo` 

Thanks again!
